set-option -g default-terminal "screen-256color"
set -s escape-time 0 

unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix
set -g status-style 'bg=#333333 fg=#5eacd3'

bind r source-file ~/.tmux.conf # Reload tmux config file with Ctrl-a + r (useful when you make changes)
set -g base-index 1 # Start numbering at 1 for easier navigation with Ctrl-a + n and Ctrl-a + p (next and previous)

# Enable mouse support for switching panes/windows
set -g mouse on

# Set-up copy mode with vi bindings 
# Usage:
#   Enter copy mode with Ctrl-a + [ 
#   Move around with vi keys (hjkl)
#   Start selection with v
#   Copy selection with y
#   Using Esc, Enter or Ctrl-c will exit copy mode
setw -g mode-keys vi 
bind-key -T copy-mode-vi 'v' send-keys -X begin-selection 
bind-key -T copy-mode-vi 'y' send-keys -X copy-pipe-and-cancel "xclip -in -selection clipboard" # Copy to clipboard, requires xclip

# vim-like  pane switching
bind -r ^ last-window
bind -r k select-pane -U
bind -r j select-pane -D
bind -r h select-pane -L
bind -r l select-pane -R

# prefix + C to create a new window in the current directory path
bind-key -r c  run-shell  "tmux neww -c '#{pane_current_path}'"

bind-key -r f run-shell "tmux neww ~/.local/bin/tmux-sessionizer"
bind-key -r . run-shell "~/.local/bin/tmux-sessionizer ~/.config/nvim/"

bind-key -r i run-shell "tmux neww ~/.dotfiles/tmux/tmux-cht.sh" # mapping prefix + i to open cht.sh
